<?php
const TITLE = 'InfinitySt<span class="text-3xl" style="vertical-align: -8%;">&infin;</span>ck';
const HOME = 'Inicio';
const RECOMMENDED = 'Recomendados';
const SEPARATOR = '>';
const BASKET = 'Cesta';
const CART_EMPTY = 'Tu cesta está vacía';
const MY_ACCOUNT = 'Mi cuenta';
const LOGIN = 'Iniciar Sesión';
const USER = 'Usuario';
const PASSWORD = 'Contraseña';
const SEARCH = 'Buscar';
const MIN_CHARS = 'Se necesitan minimo %d caracteres para buscar';
const PRODUCTS_FOUND = ' productos encontrados';
const PRODUCTS_NOT_FOUND = 'No se han encontrado resultados para ';
const NO_PRODUCTS = 'No hay productos en esta categoría';
const CURRENCY = '€';
const ADD_TO_CART = 'Añadir al carrito';
const CHECKOUT = 'Pagar';
const COPYRIGHT = 'InfinityStock™ © 2023. All Rights Reserved.';
const INSTAGRAM = 'Instagram';
const FACEBOOK = 'Facebook';
const TWITTER = 'Twitter';
const GITHUB = 'GitHub';
