<?php
const TITLE = 'InfinitySt<span class="text-3xl align-bottom">&infin;</span>ck';
const HOME = 'Inicio';
const RECOMENDADOS = 'Recomendados';
const SEPARATOR = '>';
const CESTA = 'Cesta';
const MI_CUENTA = 'Mi cuenta';
const INICIAR_SESION = 'Iniciar Sesión';
const USUARIO = 'Usuario';
const CONTRASENA = 'Contraseña';
const BUSCAR = 'Buscar';
const MINIMO_CARACTERES = 'Se necesitan minimo %d caracteres para buscar';
const PRODUCTOS_ENCONTRADOS = ' productos encontrados';
const PRODUCTOS_NO_ENCONTRADOS = 'No se han encontrado resultados para ';
const CATEGORIAS = 'Categorías';
const NO_PRODUCTS = 'No hay productos en esta categoría';
const MONEDA = '€';
const ADD_TO_CART = 'Añadir al carrito';
const COPYRIGHT = 'InfinityStock™ © 2023. All Rights Reserved.';
const INSTAGRAM = 'Instagram';
const FACEBOOK = 'Facebook';
const TWITTER = 'Twitter';
const GITHUB = 'GitHub';