INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (1, "Teléfono inteligente", "Teléfono avanzado con cámara de alta resolución.", 499.99, 4, 5);                             
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (2, "Televisor LED", "Televisor de alta definición con tecnología LED.", 699.99, 5);                                     
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (3, "Computadora portátil", "Computadora portátil potente y ligera para trabajo y entretenimiento.", 899.99, 5);         
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (4, "Auriculares inalámbricos", "Auriculares Bluetooth con cancelación de ruido.", 149.99, 5);                           
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (5, "Cámara DSLR", "Cámara réflex digital con lentes intercambiables.", 799.99, 5);                                      
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (6, "Tablet", "Tablet de última generación con pantalla táctil.", 349.99, 5);                                            
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (7, "Altavoz Bluetooth", "Altavoz portátil con conectividad Bluetooth.", 79.99, 5);                                      
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (8, "Reloj inteligente", "Reloj con seguimiento de actividad y notificaciones.", 199.99, 5);                             
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (9, "Consola de videojuegos", "Consola de juegos de alta gama para experiencias de juego inmersivas.", 499.99, 5);       
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (10, "Impresora 3D", "Impresora 3D para crear objetos tridimensionales.", 299.99, 5);                                    
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (11, "Camiseta de algodón", "Camiseta básica de algodón suave.", 19.99, 5);                                              
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (12, "Jeans ajustados", "Pantalones vaqueros ajustados y modernos.", 39.99, 5);                                          
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (13, "Vestido elegante", "Vestido de noche elegante y sofisticado.", 69.99, 5);                                          
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (14, "Chaqueta de cuero", "Chaqueta de cuero genuino con diseño moderno.", 129.99, 5);                                   
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (15, "Zapatillas deportivas", "Zapatillas cómodas para actividades deportivas.", 59.99, 5);                              
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (16, "Traje formal", "Traje completo para ocasiones formales.", 199.99, 5);                                              
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (17, "Sudadera con capucha", "Sudadera cómoda con capucha y bolsillos.", 29.99, 5);                                      
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (18, "Blusa de seda", "Blusa de seda suave y ligera.", 49.99, 5);                                                        
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (19, "Calcetines a rayas", "Calcetines divertidos con diseño a rayas.", 9.99, 5);                                        
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (20, "Abrigo de invierno", "Abrigo abrigado y resistente al viento para el invierno.", 149.99, 5);                       
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (21, "Conjunto deportivo", "Conjunto de ropa deportiva para entrenamientos intensos.", 59.99, 5);                        
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (22, "Asistente de voz inteligente", "Dispositivo que proporciona control por voz y funciones para el hogar.", 39.99, 5);
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (23, "Set de especias gourmet", "Set de especias de alta calidad para cocinar platos deliciosos.", 24.99, 5);            
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (24, "Manta suave y acogedora", "Manta de tela suave perfecta para relajarse en casa.", 29.99, 5);                       
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (25, "Auriculares inalámbricos deportivos", "Auriculares diseñados para deportes con conectividad Bluetooth.", 69.99, 5);
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (26, "Cafetera de goteo programable", "Cafetera que prepara café automáticamente con temporizador.", 49.99, 5);          
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (27, "Bicicleta estática plegable", "Bicicleta de ejercicio plegable para entrenamientos en casa.", 199.99, 5);          
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (28, "Chaqueta deportiva resistente al viento", "Chaqueta ligera y cortavientos para actividades deportivas.", 89.99, 5);
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (29, "Báscula de cocina digital", "Báscula precisa para medir ingredientes al cocinar.", 19.99, 5);                      
INSERT INTO productos (id, nombre, descripcion, precio, stock) VALUES (30, "Botella de agua deportiva", "Botella resistente y diseñada para llevar durante actividades físicas.", 12.99, 5);   
